# Generated by Django 5.0.3 on 2024-03-25 11:22

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=100, verbose_name='Codigo cuenta')),
                ('name', models.CharField(max_length=400, verbose_name='Nombre')),
            ],
        ),
        migrations.CreateModel(
            name='CarBrand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='Nombre')),
            ],
            options={
                'verbose_name': 'Marca',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CarPart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre')),
            ],
            options={
                'verbose_name': 'Item',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=' ', max_length=20, verbose_name='Nombre')),
                ('address', models.CharField(default=' ', max_length=400, verbose_name='Dirección')),
                ('phone_number', models.CharField(max_length=11, validators=[django.core.validators.RegexValidator('(\\+)*\\d{7,11}')], verbose_name='Numero Telefónico')),
            ],
            options={
                'verbose_name': 'Company',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='WindowFilm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre')),
                ('description', models.TextField()),
            ],
            options={
                'verbose_name': 'Lamina',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='BranchOffice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=' ', max_length=20, verbose_name='Nombre')),
                ('address', models.CharField(default=' ', max_length=400, verbose_name='Dirección')),
                ('enable', models.BooleanField(default=True, verbose_name='Habilitado')),
                ('empleado', models.ManyToManyField(to=settings.AUTH_USER_MODEL, verbose_name='Empleados')),
            ],
        ),
        migrations.CreateModel(
            name='CarModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='Nombre')),
                ('car_brand', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='proforma.carbrand', verbose_name='Marca')),
            ],
            options={
                'verbose_name': 'Modelo',
                'ordering': ['car_brand'],
            },
        ),
        migrations.CreateModel(
            name='CarModelPart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('width', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Ancho')),
                ('length', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Largo')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Cantidad')),
                ('installation_price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Precio Instalación')),
                ('car_model', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='proforma.carmodel', verbose_name='Modelo')),
                ('car_part', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='proforma.carpart', verbose_name='Item')),
            ],
            options={
                'verbose_name': 'Modelo Item',
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=400, verbose_name='Nombre')),
                ('last_name', models.CharField(max_length=400, verbose_name='Apellido')),
                ('phone_number', models.CharField(max_length=11, validators=[django.core.validators.RegexValidator('(\\+)*\\d{7,11}')], verbose_name='Numero Telefónico')),
                ('ci_nit', models.CharField(max_length=20, validators=[django.core.validators.RegexValidator('\\d*')], verbose_name='CI/NIT')),
                ('type', models.CharField(choices=[('syst', 'System'), ('clie', 'Client'), ('inst', 'Instalador')], default='client', max_length=10, verbose_name='Tipo Perfil')),
                ('is_enable', models.BooleanField(default=True)),
                ('sucursal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='proforma.branchoffice')),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Perfil',
                'ordering': ['last_name', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Account_Flow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('debe', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Debe')),
                ('haber', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Haber')),
                ('saldo', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Saldo')),
                ('created_on', models.DateTimeField(verbose_name='Creado en')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='proforma.account', verbose_name='Cuenta')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='proforma.profile', verbose_name='Creador Por')),
            ],
        ),
        migrations.CreateModel(
            name='ProformaHeader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now=True, verbose_name='Fecha Proforma')),
                ('name', models.CharField(default=' ', max_length=400, verbose_name='Nombre Completo')),
                ('email', models.CharField(max_length=100, null=True, validators=[django.core.validators.EmailValidator()], verbose_name='Email')),
                ('ci_nit', models.CharField(max_length=20, null=True, validators=[django.core.validators.RegexValidator('\\d*')], verbose_name='CI/NIT')),
                ('car_plate', models.CharField(blank=True, default='', max_length=10, null=True, verbose_name='Placa Auto')),
                ('phone_number', models.CharField(default='', max_length=11, validators=[django.core.validators.RegexValidator('(\\+)*\\d{7,11}')], verbose_name='Numero Telefónico')),
                ('discount', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.DecimalValidator(decimal_places=2, max_digits=10), django.core.validators.MinValueValidator(limit_value=0)], verbose_name='Descuento')),
                ('discount_reason', models.TextField(blank=True, null=True, verbose_name='Motivo Descuento')),
                ('total_price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Total Pagar')),
                ('is_delete', models.BooleanField(default=False)),
                ('is_close', models.BooleanField(default=False)),
                ('branch_office', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='proforma.branchoffice', verbose_name='Sucursal')),
                ('car_model', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='proforma.carmodel', verbose_name='Modelo')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='proforma_created_by', to='proforma.profile', verbose_name='Creado Por')),
            ],
            options={
                'verbose_name': 'Proforma',
                'ordering': ['-id', '-created_on'],
            },
        ),
        migrations.CreateModel(
            name='PaymentNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_method', models.CharField(choices=[('bank', 'Banco'), ('cash', 'Efectivo')], default='bank', max_length=8, verbose_name='Tipo Trabajador')),
                ('created_on', models.DateTimeField(verbose_name='Creado en')),
                ('total_price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Total Pagar')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='proforma.profile', verbose_name='Creador Por')),
                ('proforma', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='proforma.proformaheader', verbose_name='Nota Trabajo')),
            ],
        ),
        migrations.CreateModel(
            name='Storage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_length', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Longitud Inicial')),
                ('created_on', models.DateTimeField(verbose_name='Fecha')),
                ('numero_referencia', models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(limit_value=9999999999, message='solo se aceptan valores con 10 digitos')], verbose_name='Numero Referencia')),
                ('precio_compra_mtr_lineal', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Precio Compra Metro Lineal')),
                ('precio_venta_mtr_lineal', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Precio Venta Metro Lineal')),
                ('branch_office', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='sucursal_inventario_in', to='proforma.branchoffice', verbose_name='Sucursal')),
            ],
        ),
        migrations.CreateModel(
            name='StorageOut',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(verbose_name='Creado en')),
                ('length_sold', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Metros Cortados')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Anulado')),
                ('deleted_on', models.DateTimeField(null=True, verbose_name='Eliminado en')),
                ('branch_office', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='sucursal_inventario_out', to='proforma.branchoffice', verbose_name='Sucursal')),
                ('storage', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='sucursal_inventario', to='proforma.storage', verbose_name='Almacen')),
            ],
        ),
        migrations.CreateModel(
            name='Proforma_Detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('width', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Ancho')),
                ('length', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Largo')),
                ('sub_total', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Sub Total')),
                ('installation_price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Costo Instalación')),
                ('window_film_price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Costo Lámina')),
                ('quantity', models.PositiveIntegerField(default=0, verbose_name='Cantidad')),
                ('car_part', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='proforma.carpart', verbose_name='Item')),
                ('proforma_header', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='items', to='proforma.proformaheader', verbose_name='Proforma')),
                ('window_film', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='proforma.windowfilm', verbose_name='Lámina')),
            ],
            options={
                'verbose_name': 'Detalle Venta',
            },
        ),
        migrations.CreateModel(
            name='WindowFilmReel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('width', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Ancho')),
                ('length', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Largo')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio')),
                ('window_film', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='bobina_lamina', to='proforma.windowfilm', verbose_name='Lamina')),
            ],
            options={
                'verbose_name': 'Bobina',
                'ordering': ['window_film'],
            },
        ),
        migrations.AddField(
            model_name='storage',
            name='reel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='bobina_inventario', to='proforma.windowfilmreel', verbose_name='Bobina'),
        ),
        migrations.CreateModel(
            name='WorkNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_garantia', models.CharField(blank=True, max_length=12, null=True, unique=True, verbose_name='Codigo Garantia')),
                ('car_in_date', models.DateTimeField(blank=True, null=True, verbose_name='Entrada Vehiculo')),
                ('car_out_date', models.DateTimeField(blank=True, null=True, verbose_name='Salida Vehiculo')),
                ('created_on', models.DateTimeField(verbose_name='Creado en')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Observaciones')),
                ('proforma', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='proforma.proformaheader', verbose_name='Proforma')),
            ],
            options={
                'verbose_name': 'Nota Trabajo',
                'ordering': ['-id', '-created_on'],
            },
        ),
        migrations.CreateModel(
            name='WorkNoteSumary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('width', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Ancho')),
                ('length', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Largo')),
                ('created_on', models.DateTimeField(verbose_name='Creado en')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Anulado')),
                ('deleted_on', models.DateTimeField(null=True, verbose_name='Eliminado en')),
                ('storage_out', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='proforma.storageout', verbose_name='registro salida inventario')),
                ('work_note', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='proforma.worknote', verbose_name='Nota Trabajo')),
            ],
        ),
        migrations.CreateModel(
            name='WorkNoteWorker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('inst', 'Instalador'), ('resp', 'Responsable'), ('instalador', 'Instalador')], default='responsable', max_length=11, verbose_name='Tipo Trabajador')),
                ('created_on', models.DateTimeField(verbose_name='Creado en')),
                ('work_note', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='proforma.worknote', verbose_name='Nota Trabajo')),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='proforma.profile', verbose_name='Trabajador')),
            ],
        ),
        migrations.AddConstraint(
            model_name='carmodelpart',
            constraint=models.UniqueConstraint(fields=('car_model', 'car_part'), name='unique_model_item'),
        ),
    ]
