# Generated by Django 5.0.3 on 2024-03-26 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proforma', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='carbrand',
            name='is_enable',
            field=models.BooleanField(default=True, verbose_name='Habilitado'),
        ),
    ]
