# Generated by Django 5.0.3 on 2024-04-02 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proforma', '0004_carpart_is_enable'),
    ]

    operations = [
        migrations.AddField(
            model_name='carmodelpart',
            name='is_enable',
            field=models.BooleanField(default=True, verbose_name='Habilitado'),
        ),
    ]
